### ISSUE TITLE
Не работает, как в 

### ISSUE THREAD

**Issue by andech** [it-projects-llc/l10n-addons#14]
l10n_ru_2 через магазин приложений не устанавливается, пишет: "The one-click installation of Odoo Apps is currently unavailable. Please go to www.odoo.com/apps to download manually."
Если вручную скопировать в папку addons, то odoo 10 при перезапуске не запускается до удаления папки с этим модулем.
Модуль l10n_ru, который делает что-то похожее, устанавливается без проблем.
Проверял на локалке.

**Comment by yelizariev** [comment]
Мы не проверяли под 10.0, там может не работать. 
Также, могу посоветовать попробовать переименовать модуль на l10n_ru, т.к. имеется требования на это имя.
Но более точнее можно что-то сказать, если будет лог ошибок

**Comment by andech** [comment]
Переименовал, ничего не изменилось.
Если под Odoo 10 не проверяли, то понятно, просто в магазине приложений написано, что работает под этой версией.
В консоли пишет следующее:

2017-06-29 14:25:33,365 7360 INFO ? odoo: Odoo version 10.0-20170614
2017-06-29 14:25:33,367 7360 INFO ? odoo: Using configuration file at C:\Program Files (x86)\Odoo 10.0\server\odoo.conf
2017-06-29 14:25:33,368 7360 INFO ? odoo: addons paths: ['C:\\Users\\Main\\AppData\\Local\\OpenERP S.A.\\Odoo\\addons\\10.0', u'C:\\Program Files (x86)\\Odoo 10.0\\server\\odoo\\addons']
2017-06-29 14:25:33,371 7360 INFO ? odoo: database: openpg@localhost:5432
2017-06-29 14:25:33,387 7360 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2017-06-29 14:26:29,921 7360 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres
2017-06-29 14:26:30,270 7360 INFO ? werkzeug: 127.0.0.1 - - [29/Jun/2017 14:26:30] "GET /web?debug HTTP/1.1" 500 -
2017-06-29 14:26:30,279 7360 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "werkzeug\serving.py", line 177, in run_wsgi

  File "werkzeug\serving.py", line 165, in execute

  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\service\server.py", line 250, in app
    return self.app(e, s)
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\service\wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\service\wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 1305, in __call__
    self.load_addons()
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 1326, in load_addons
    m = __import__('odoo.addons.' + module)
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\modules\module.py", line 81, in load_module
    execfile(modfile, new_mod.__dict__)
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\l10n_ru\__init__.py", line 1, in <module>
    import l10n_ru
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\l10n_ru\l10n_ru.py", line 3, in <module>
    from openerp.osv import fields, osv
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\modules\module.py", line 109, in load_module
    mod = importlib.import_module(canonical)
  File "importlib\__init__.py", line 37, in import_module

ImportError: No module named fields
